version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: Alexs
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Lab3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  serv_user:
    build:
      context: .
      dockerfile: serv_user/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: Lab3
      DB_USER: Alexs
      DB_PASSWORD: root

  serv_project:
    build:
      context: .
      dockerfile: serv_project/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: Lab3
      DB_USER: Alexs
      DB_PASSWORD: root

  serv_task:
    build:
      context: .
      dockerfile: serv_task/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: Lab3
      DB_USER: Alexs
      DB_PASSWORD: root

volumes:
  postgres_data:
